[package]
name = "rterm-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
dirs.workspace = true
log.workspace = true
russh.workspace = true
russh-sftp.workspace = true
rterm-config.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
