[package]
name = "rterm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
dirs.workspace = true
log.workspace = true
russh.workspace = true
russh-sftp.workspace = true
rterm-config.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
