[package]
name = "rterm-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs.workspace = true
fontdb.workspace = true
futures.workspace = true
iced.workspace = true
iced_widget.workspace = true
iced_aw.workspace = true
alacritty_terminal.workspace = true
anyhow.workspace = true
iced_core.workspace = true
iced_graphics.workspace = true
open.workspace = true
polling.workspace = true
piper.workspace = true
log.workspace = true
rfd.workspace = true
reqwest.workspace = true
rust-i18n.workspace = true
semver.workspace = true
serde.workspace = true
rterm-config.workspace = true
rterm-crypto.workspace = true
rterm-core.workspace = true
tokio.workspace = true
keyring.workspace = true

[dev-dependencies]
iced_runtime.workspace = true
